{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "VERSION = '07_v1_03'\n",
    "\n",
    "model_name_list = [\n",
    "#     'microsoft/deberta-base',\n",
    "#     'microsoft/deberta-v3-base',\n",
    "#     'microsoft/deberta-large',\n",
    "#     'microsoft/deberta-large-mnli',\n",
    "#     'microsoft/deberta-xlarge',\n",
    "#     'microsoft/deberta-v2-xlarge',\n",
    "#     'microsoft/deberta-v3-large',\n",
    "#     'roberta-base',\n",
    "#     'roberta-large',\n",
    "    'google/electra-base-discriminator',\n",
    "    'google/electra-large-discriminator',\n",
    "    'deepset/roberta-base-squad2',\n",
    "    'deepset/roberta-large-squad2',\n",
    "    'xlm-roberta-base',\n",
    "    'xlm-roberta-large',\n",
    "    'distilroberta-base',\n",
    "    #'distilroberta-large',\n",
    "    'albert-large-v2',\n",
    "    'bert-large-cased-whole-word-masking',\n",
    "    'bert-large-cased',\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "google/electra-base-discriminator\n",
      "2022-10-09 19:20:35.271626: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:20:35.271646: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  google/electra-base-discriminator\n",
      "Some weights of the model checkpoint at google/electra-base-discriminator were not used when initializing ElectraModel: ['discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.bias']\n",
      "- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [00:45<00:00, 10.66it/s]\n",
      "embeds.shape =  (3911, 768)\n",
      "embed.shape =  (3911, 768)\n",
      "google/electra-large-discriminator\n",
      "2022-10-09 19:21:37.663904: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:21:37.663927: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  google/electra-large-discriminator\n",
      "Some weights of the model checkpoint at google/electra-large-discriminator were not used when initializing ElectraModel: ['discriminator_predictions.dense.bias', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.weight']\n",
      "- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [02:33<00:00,  3.19it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n",
      "deepset/roberta-base-squad2\n",
      "2022-10-09 19:24:29.534367: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:24:29.534391: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  deepset/roberta-base-squad2\n",
      "Some weights of the model checkpoint at deepset/roberta-base-squad2 were not used when initializing RobertaModel: ['qa_outputs.weight', 'qa_outputs.bias']\n",
      "- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "Some weights of RobertaModel were not initialized from the model checkpoint at deepset/roberta-base-squad2 and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "100%|█████████████████████████████████████████| 489/489 [00:49<00:00,  9.85it/s]\n",
      "embeds.shape =  (3911, 768)\n",
      "embed.shape =  (3911, 768)\n",
      "deepset/roberta-large-squad2\n",
      "2022-10-09 19:25:37.375794: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:25:37.375818: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  deepset/roberta-large-squad2\n",
      "Some weights of the model checkpoint at deepset/roberta-large-squad2 were not used when initializing RobertaModel: ['qa_outputs.weight', 'qa_outputs.bias']\n",
      "- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "Some weights of RobertaModel were not initialized from the model checkpoint at deepset/roberta-large-squad2 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "100%|█████████████████████████████████████████| 489/489 [02:43<00:00,  3.00it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n",
      "xlm-roberta-base\n",
      "2022-10-09 19:28:40.013502: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:28:40.013526: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  xlm-roberta-base\n",
      "Downloading: 100%|██████████████████████████████| 615/615 [00:00<00:00, 198kB/s]\n",
      "Downloading: 100%|█████████████████████████| 4.83M/4.83M [00:01<00:00, 2.55MB/s]\n",
      "Downloading: 100%|█████████████████████████| 8.68M/8.68M [00:02<00:00, 3.06MB/s]\n",
      "Downloading: 100%|█████████████████████████| 1.04G/1.04G [02:03<00:00, 9.03MB/s]\n",
      "Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.dense.weight']\n",
      "- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [00:47<00:00, 10.25it/s]\n",
      "embeds.shape =  (3911, 768)\n",
      "embed.shape =  (3911, 768)\n",
      "xlm-roberta-large\n",
      "2022-10-09 19:31:56.981865: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:31:56.981889: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  xlm-roberta-large\n",
      "Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']\n",
      "- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100%|█████████████████████████████████████████| 489/489 [02:31<00:00,  3.23it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n",
      "distilroberta-base\n",
      "2022-10-09 19:34:48.228323: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:34:48.228345: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  distilroberta-base\n",
      "Some weights of the model checkpoint at distilroberta-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.bias']\n",
      "- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [00:24<00:00, 20.20it/s]\n",
      "embeds.shape =  (3911, 768)\n",
      "embed.shape =  (3911, 768)\n",
      "distilroberta-large\n",
      "2022-10-09 19:35:29.491335: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:35:29.491359: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  distilroberta-large\n",
      "401 Client Error: Unauthorized for url: https://huggingface.co/distilroberta-large/resolve/main/config.json\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py\", line 593, in _get_config_dict\n",
      "    user_agent=user_agent,\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/file_utils.py\", line 1854, in cached_path\n",
      "    local_files_only=local_files_only,\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/file_utils.py\", line 2050, in get_from_cache\n",
      "    _raise_for_status(r)\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/file_utils.py\", line 1977, in _raise_for_status\n",
      "    request.raise_for_status()\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/requests/models.py\", line 943, in raise_for_status\n",
      "    raise HTTPError(http_error_msg, response=self)\n",
      "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/distilroberta-large/resolve/main/config.json\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"../07_v1_03/extract_embeddings.py\", line 128, in <module>\n",
      "    embed = get_embeddings(args.model_name, train_df, args)\n",
      "  File \"../07_v1_03/extract_embeddings.py\", line 46, in get_embeddings\n",
      "    tokenizer = AutoTokenizer.from_pretrained(model_name, trim_offsets=False)\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py\", line 471, in from_pretrained\n",
      "    pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py\", line 612, in from_pretrained\n",
      "    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py\", line 537, in get_config_dict\n",
      "    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)\n",
      "  File \"/home/takesako/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py\", line 619, in _get_config_dict\n",
      "    \"We couldn't connect to 'https://huggingface.co/' to load this model and it looks like \"\n",
      "OSError: We couldn't connect to 'https://huggingface.co/' to load this model and it looks like distilroberta-large is not the path to a directory conaining a config.json file.\n",
      "Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.\n",
      "albert-large-v2\n",
      "2022-10-09 19:35:33.442494: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:35:33.442523: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  albert-large-v2\n",
      "Some weights of the model checkpoint at albert-large-v2 were not used when initializing AlbertModel: ['predictions.LayerNorm.weight', 'predictions.dense.bias', 'predictions.bias', 'predictions.decoder.bias', 'predictions.decoder.weight', 'predictions.LayerNorm.bias', 'predictions.dense.weight']\n",
      "- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [02:57<00:00,  2.76it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n",
      "bert-large-cased-whole-word-masking\n",
      "2022-10-09 19:38:45.628008: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:38:45.628032: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  bert-large-cased-whole-word-masking\n",
      "Some weights of the model checkpoint at bert-large-cased-whole-word-masking were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']\n",
      "- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "100%|█████████████████████████████████████████| 489/489 [02:35<00:00,  3.14it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n",
      "bert-large-cased\n",
      "2022-10-09 19:41:38.891126: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:\n",
      "2022-10-09 19:41:38.891151: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "model_name =  bert-large-cased\n",
      "Some weights of the model checkpoint at bert-large-cased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias']\n",
      "- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100%|█████████████████████████████████████████| 489/489 [02:35<00:00,  3.15it/s]\n",
      "embeds.shape =  (3911, 1024)\n",
      "embed.shape =  (3911, 1024)\n"
     ]
    }
   ],
   "source": [
    "for MODEL_NAME in model_name_list:\n",
    "    print(MODEL_NAME)\n",
    "    !python ../$VERSION/extract_embeddings.py --version $VERSION --model_name $MODEL_NAME"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
